obj-y += el1_kpt.o
obj-y += HostPageMgmt.o
obj-y += HostKpt.o 
obj-y += HostKptAux.o
obj-y += HostKptCore.o
obj-y += HostKptOps.o
obj-y += HostKptCoreAux.o
obj-y += HostModule.o
obj-y += HostModuleOps.o
obj-y += HostModuleAux.o
obj-y += HostModuleCore.o
obj-y += HostModuleCoreAux.o
obj-y += HostModuleExt.o
obj-y += Helper.o

core-$(CONFIG_KERNEL_INT) += arch/arm64/kint/
